# 对话设置
conversation_setting:

  system: "现在你是一位金牌非遗讲解员，你的名字叫{role_type}，你的说话方式是{character}。你能够根据非遗信息讲解非遗并且结合非遗信息解答用户提出的疑问。"
  first_input: "我的{product_info}，你需要根据我给出的非遗信息撰写一段非遗讲解文案。你需要突出非遗项目的独特魅力和文化价值，激发听众的兴趣和尊重。"


# 数据集生成设置
data_generation_setting:

  # 每个产品生成 ${each_product_gen} 个 conversion 数据，conversion 中包含【文案 + QA】，
  each_product_gen: 3

  # 每个 conversion 中的的对话数，文案为 1 个，其余会生成 ${each_conversation_qa} - 1 个 QA 
  each_conversation_qa: 5

  # 每个文案生成随机抽取 ${each_pick_hightlight} 个亮点
  each_pick_hightlight: 3

  # 每个文案生成后随机抽取 ${each_pick_hightlight} 个问题生成用户的提问
  each_pick_question: 3

  # 数据集生成 prompt
  dataset_gen_prompt: 现在你是一位金牌非遗讲解员，你的名字叫{role_type}，你的说话方式是{character}。
                      我的{product_info}，你需要根据我给出的非遗产品信息撰写一段至少600字的直播讲解文案。你需要深入挖掘并放大产品的非遗文化价值，激发观众的兴趣，同时传递对非遗文化的尊重与热爱。
                      输出文案后，结合非遗产品信息站在观众的角度根据[{customer_question}]提出{each_conversation_qa}个问题并解答。
                      全部输出的信息使用我期望的 json 格式进行输出：{dataset_json_format}。注意 json 一定要合法。
 
  # 数据生成 json 格式
  dataset_json_format: 
    '{
      "conversation": [
        {
          "output": 非遗讲解文案，格式化一行输出，不要换行。
        },
        {
          "input": 观众的问题,
          "output": 讲解员回答
        },
        {
          "input": 观众的问题,
          "output": 讲解员回答
        },
        ... 直到问题结束
      ]
    }'

# 说明书生成设置
instruction_generation_setting:
  # 说明书生成 prompt
  dataset_gen_prompt: 我上传的是一个非遗的详细说明，请帮我生成 markdwon 格式的说明书，需要包含项目名称、历史渊源、文化内涵、表现形式、社会价值与影响，越详细越好，只输出说明书即可。


# 角色及其性格
role_type:
  乐乐喵: # 萝莉
    - 知识渊博
    - 讲解生动
    - 熟练运用非遗相关的历史与文化典故
    - 称呼观众为[亲爱的朋友们]

# 商品信息结构体
product_info_struct:
  - 非遗名是[{name}]，
  - 非遗的亮点是[{highlights}]

# prompt: 购买东西时候，客户常会问题的问题，举例10个, 只列举大类就行
customer_question_type:
  - 历史背景与文化渊源
  - 制作工艺与技艺特点
  - 材质选择与处理
  - 传承人与传承情况
  - 展览信息与参观流程
  - 保护措施与现状
  - 作品欣赏与解读
  - 文化价值与意义
  - 互动体验与参与方式
  - 后续发展与推广计划

# 第一个 prompt: 帮我列举10种常用的消费品种类，并每种举例5个其子类
# 每个类 prompt: 现在你精通任何产品，你可以帮我举例每个产品的6个亮点或特点，, 然后用python dict形式输出：{类名：[特点1, 特点2] ...} ，去掉特点12的字样，除python字典外的其他都不要输出，不要有任何的警告信息。 [xxx]
product_list:
  民间文学:
    神话:
      盘古开天辟地: [创世主题, 英雄主义, 象征意义, 宇宙观, 自然崇拜, 口耳相传]
      女娲补天: [拯救世界, 母性光辉, 象征意义, 宇宙秩序, 自然灾害, 人类起源]
      精卫填海: [坚持不懈, 复仇与抗争, 象征意义, 自然力量, 悲剧色彩, 民族精神]
      夸父逐日: [追求光明, 英雄主义, 象征意义, 自然崇拜, 悲剧结局, 探索精神]
      后羿射日: [英雄救世, 勇敢无畏, 象征意义, 自然灾害的克服, 射箭技艺, 神话色彩]
    民间传说:
      孟姜女哭长城: [爱情悲剧, 忠诚与牺牲, 社会批判, 文化符号, 女性形象, 民间情感]
      牛郎织女: [爱情忠贞, 家庭团圆, 星象传说, 七夕节日, 封建礼教批判, 文化传承]
      梁祝传说: [爱情悲剧, 家庭阻力, 性别角色, 文化传承, 民间信仰, 美好愿景]
      白蛇传: [人妖之恋, 爱情考验, 法海阻挠, 忠贞不渝, 文化象征, 世代传承]
      西湖龙井的传说: [茶文化, 善良与抗争, 地方特色, 民间故事, 茶树象征, 文化传承]
    民间故事:
      杜康酿酒: [偶然发现, 酿酒技艺, 人物传奇, 历史背景, 文化寓意, 智慧启示]
      阿凡提的故事: [智慧与幽默, 社会批判, 人物形象, 正义与邪恶, 讽刺艺术, 民间智慧]
      三个和尚: [团结合作, 互相推诿, 教训寓意, 寺庙生活, 传统寓言, 道德启示]
      田螺姑娘: [爱情故事, 善良勤劳, 美好愿望, 人物形象, 幸福生活, 民间奇谈]
      长发妹: [勇敢抗争, 泉水发现, 山妖威胁, 村民福祉, 英雄形象, 乡土传奇]
    民间歌谣:
      歌谣《茉莉花》: [旋律优美, 歌词深情, 自然意象, 情感共鸣, 广泛流传, 民俗歌曲]
      歌谣《小白菜》: [悲情主题, 儿童视角, 生活苦难, 社会现实, 情感表达, 传统儿歌]
      歌谣《摇篮曲》: [温柔舒缓, 哄婴入睡, 母爱表达, 文化传统, 安抚作用, 民间摇篮曲]
      歌谣《采茶扑蝶》: [劳动场景, 欢乐气氛, 自然意象, 民间生活, 文化传承, 乡土歌谣]
      歌谣《十二生肖歌》: [生肖文化, 动物形象, 寓教于乐, 知识普及, 文化传统, 生肖歌谣]
    民间叙事诗:
      叙事诗《格萨尔王传》: [长篇史诗, 英雄传奇, 民族历史, 社会正义, 口头传统, 文化传承]
      叙事诗《木兰辞》: [女性英雄, 爱国情怀, 家庭责任, 战争经历, 性别平等, 诗歌艺术]
      叙事诗《长恨歌》: [爱情故事, 历史背景, 悲剧结局, 人物命运, 诗歌情感, 文化传承]
      叙事诗《孔雀东南飞》: [爱情悲剧, 离别思念, 人物形象, 文化传承, 民间叙事, 情感表达]
      叙事诗《秦香莲》: [爱恨情仇, 背叛复仇, 法律正义, 人物命运, 民间叙事, 道德评判]
  传统音乐:
    民间音乐:
      音乐《茉莉花》: [旋律优美, 歌词深情, 广泛流传, 民族特色, 情感共鸣, 易于哼唱]
      音乐《小白菜》: [悲情主题, 歌词直白, 情感真挚, 反映生活, 历史传承, 民间故事]
      音乐《康定情歌》: [情歌典范, 地域风情, 旋律欢快, 情感热烈, 民族乐器, 文化传承]
      音乐《信天游》: [陕北民歌, 富有哲理, 情感直接, 高亢激昂, 生活气息, 民族风情]
      音乐《二泉映月》: [二胡独奏, 旋律悲凉, 情感丰富, 民族乐器代表, 经典之作, 技艺精湛]
    宗教音乐:
      佛教《大悲咒》: [宁静致远, 净化心灵, 旋律悠扬, 宗教氛围, 普度众生, 精神寄托]
      佛教《心经》: [智慧启迪, 心灵平静, 旋律简单, 禅意深远, 修行指南, 文化传承]
      道教《道德经》: [道家哲学, 旋律古朴, 宁静致远, 自然和谐, 修行助缘, 文化瑰宝]
      基督教《平安夜》: [圣诞颂歌, 温馨祥和, 世界和平, 旋律优美, 情感真挚, 宗教节日]
      伊斯兰教《古兰经》: [宗教经典, 虔诚敬畏, 旋律庄重, 信仰表达, 文化传承, 心灵净化]
    宫廷音乐:
      宫廷雅韵《高山流水》: [意境深远, 旋律优美, 宫廷雅乐, 自然象征, 友情寓意, 文人情怀]
      古曲瑰宝《广陵散》: [古代名曲, 旋律激昂, 历史背景, 技艺精湛, 情感丰富, 文化瑰宝]
      战乐史诗《十面埋伏》: [战争题材, 旋律紧张, 技巧复杂, 气势磅礴, 历史再现, 民族乐器]
      宫廷画卷《春江花月夜》: [意境如画, 旋律悠扬, 宫廷合奏, 自然美景, 情感细腻, 文化传承]
      月下筝音《汉宫秋月》: [宫廷筝曲, 旋律悲凉, 情感深沉, 历史背景, 宫廷生活, 民族乐器]
    器乐音乐:
      古筝曲《渔舟唱晚》: [意境优美, 旋律悠扬, 古筝音色, 生活场景, 情感细腻, 文化传承]
      琵琶曲《十面埋伏》: [战争题材, 技巧精湛, 琵琶音色, 气势磅礴, 历史再现, 民族乐器]
      二胡曲《二泉映月》: [悲凉意境, 情感丰富, 二胡音色, 技艺精湛, 历史背景, 文化瑰宝]
      笛子曲《姑苏行》: [江南风情, 旋律优美, 笛子音色, 生活场景, 情感真挚, 文化传承]
      古琴曲《平沙落雁》: [意境深远, 旋律古朴, 古琴音色, 自然象征, 文人情怀, 文化传承]
    歌舞音乐:
      云南《阿细跳月》: [民族歌舞, 欢快热烈, 舞蹈动作, 民族风情, 情感真挚, 文化传承]
      藏族《锅庄舞》音乐: [藏族风情, 旋律悠扬, 舞蹈动作, 生活场景, 情感热烈, 文化传承]
      京剧《霸王别姬》唱腔: [京剧经典, 唱腔独特, 历史背景, 情感真挚, 技艺精湛, 文化传承]
      越剧《红楼梦》选段: [越剧经典, 唱腔柔美, 情感细腻, 历史背景, 文化传承, 艺术魅力]
      蒙古族《那达慕大会》歌舞音乐: [蒙古族风情, 旋律欢快, 舞蹈动作, 生活场景, 情感真挚, 文化传承]
  传统舞蹈:
    民族舞蹈:
      蒙古族马舞: [草原风情, 马背文化, 服饰华丽, 音乐激昂, 团体协作, 动作豪放]
      傣族孔雀舞: [孔雀形象, 服饰鲜艳, 音乐柔美, 动作细腻, 寓意吉祥, 民族文化]
      藏族锅庄舞: [高原文化, 服饰厚重, 节奏鲜明, 舞蹈稳健, 宗教色彩, 团体协作]
      维吾尔族手鼓舞: [手鼓道具, 服饰多彩, 节奏明快, 动作丰富, 民族热情, 舞蹈技巧]
      朝鲜族长鼓舞: [长鼓道具, 服饰简洁, 节奏明快, 动作流畅, 民族韵律, 舞蹈艺术]
    宫廷舞蹈:
      唐代霓裳羽衣舞: [服饰华丽, 动作飘逸, 音乐悠扬, 场面宏大, 寓意吉祥, 宫廷文化]
      宋代队舞: [队列整齐, 服饰鲜明, 节奏明快, 表演多样, 宫廷礼仪, 舞蹈规范]
      元代宫廷宴乐舞: [文化融合, 服饰华丽, 音乐丰富, 表演灵活, 皇家气派, 宫廷娱乐]
      清代宫廷雅乐舞: [服饰庄重, 动作规范, 音乐典雅, 舞蹈庄重, 寓意深远, 宫廷礼仪]
      汉代宫廷踏歌: [步伐稳健, 服饰简约, 感染力强, 表演多样, 宫廷文化, 舞蹈节奏]
    宗教舞蹈:
      佛教跳神舞: [神灵形象, 服饰神秘, 音乐庄重, 动作模仿神灵, 寓意祈福, 佛教信仰]
      道教斋醮舞: [修炼主题, 服饰简朴, 音乐宁静, 动作缓慢有力, 寓意净化心灵, 道教精神]
      伊斯兰教苏菲舞: [旋转动作, 服饰简洁, 节奏明快, 场面热烈, 寓意净化心灵, 苏菲主义]
      印度教婆罗门舞: [手势复杂, 服饰华丽, 音乐悠扬, 舞蹈庄重, 寓意祈福净化, 婆罗门文化]
      藏传佛教金刚舞: [金刚形象, 服饰神秘, 节奏鲜明, 动作有力, 寓意驱邪, 藏传佛教信仰]
    民间舞蹈:
      汉族扇子舞: [扇子道具, 服饰简洁大方, 音乐节奏明快, 动作柔美, 表演形式灵活, 汉族文化]
      东北秧歌舞: [步伐稳健, 服饰色彩鲜艳, 音乐热烈, 表演形式多样, 东北地域特色, 舞蹈节奏]
      云南花灯舞: [花灯道具, 服饰华丽, 音乐柔美, 动作轻盈, 表演形式独特, 云南民族风情]
      安徽花鼓灯: [花鼓道具, 服饰色彩丰富, 音乐节奏感强, 动作活泼, 安徽文化, 舞蹈技巧]
      山东胶州秧歌: [步伐有力, 服饰简朴大方, 音乐热情洋溢, 表演形式热情奔放, 山东地域特色, 舞蹈艺术]
    现代舞蹈与传统舞蹈的融合:
      现代蒙古舞《草原记忆》: [融合现代元素, 动作创新, 服饰简洁, 音乐节奏鲜明, 表演新颖, 蒙古族文化与现代艺术结合]
      当代傣族孔雀舞《金孔雀》: [保留传统元素, 融入现代技巧, 服饰华丽, 音乐柔美, 表演独特, 傣族文化与现代艺术融合]
      融合京剧元素的现代舞《水袖情》: [结合京剧元素, 融入现代舞蹈, 服饰华丽, 音乐节奏明快, 表演新颖, 京剧与现代舞蹈结合]
      结合街舞与藏族舞的《雪山飞狐》: [融合街舞与藏族舞, 动作创新, 服饰简洁, 音乐节奏鲜明, 表演独特, 藏族文化与街舞文化交融]
      古典芭蕾与汉族民间舞的《扇舞丹青》: [结合古典芭蕾与汉族民间舞, 动作优雅, 服饰华丽, 音乐悠扬, 表演新颖, 中西方舞蹈艺术融合]
  传统戏剧:
    戏曲剧种:
      京剧《霸王别姬》: [古典艺术, 历史背景, 英雄美人, 京剧唱腔, 情感纠葛, 服饰美学]
      昆曲《牡丹亭》: [传统美学, 爱情主题, 诗意舞台, 昆曲韵律, 古典文学融合, 情感细腻表达]
      川剧《变脸》: [戏剧特技展示, 人物性格刻画, 剧情张力, 川剧声腔, 视觉冲击力, 文化传承价值]
      秦腔《三滴血》: [西北风情, 历史题材演绎, 家族恩怨纠葛, 秦腔独特韵味, 情感深度挖掘, 情节跌宕起伏]
      河北梆子《王宝钏》: [北方戏曲魅力, 爱情忠贞颂扬, 人物命运波折, 梆子激昂唱腔, 剧情紧凑安排, 舞台表现力]
    木偶戏:
      泉州提线木偶戏《钟馗醉酒》: [传统手工艺, 木偶灵动演绎, 角色鲜活呈现, 剧情引人入胜, 舞台视觉盛宴, 文化精髓传承]
      漳州布袋木偶戏《大名府》: [布袋木偶艺术, 故事情节丰富, 角色性格鲜明, 舞台布景精美, 文化内涵深厚, 观众互动体验]
      广东潮州铁枝木偶戏《陈三五娘》: [铁枝技艺独特, 爱情故事凄美, 剧情连贯流畅, 舞台道具考究, 地域特色浓郁, 艺术魅力展现]
      湖南杖头木偶戏《武松打虎》: [杖头操纵技巧, 人物形象生动, 动作设计巧妙, 舞台效果震撼, 传统文化弘扬, 观众情感共鸣]
      福建晋江布袋木偶戏《李逵负荆》: [布袋木偶表演, 故事情节紧凑, 角色性格突出, 舞台灯光映衬, 表演艺术精湛, 观众审美享受]
    皮影戏:
      华阴皮影戏《蟠桃会》: [皮影艺术瑰宝, 神话故事再现, 剧情发展扣人心弦, 舞台设计匠心独运, 视听享受非凡, 传统文化弘扬]
      环县道情皮影戏《卖水记》: [道情皮影融合, 剧情紧凑生动, 舞台调度合理, 地域文化展现, 皮影技艺精湛, 观众情感体验]
      唐山皮影戏《五峰会》: [皮影艺术魅力, 故事情节跌宕, 角色塑造立体, 舞台灯光绚丽, 音乐伴奏和谐, 文化内涵丰富]
      复州皮影戏《双锁山》: [皮影表演艺术, 剧情反转精彩, 角色性格鲜明, 舞台效果震撼, 传统文化传承, 观众审美愉悦]
      海宁皮影戏《水漫金山》: [皮影技艺精湛, 故事情节扣人心弦, 角色多样生动, 舞台布景精美绝伦, 视听效果震撼, 地域文化传承]
    歌舞剧:
      云南花灯歌舞剧《小河淌水》: [花灯艺术展现, 歌舞表演生动, 剧情发展引人入胜, 舞台效果绚丽多彩, 音乐旋律悠扬, 地域风情浓郁]
      贵州侗族大歌歌舞剧《蝉之歌》: [侗族大歌魅力, 歌舞元素融合, 歌词寓意深远, 舞台布景诗意盎然, 文化传承有力, 观众情感共鸣]
      蒙古族那达慕大会歌舞剧《马背上的婚礼》: [那达慕文化呈现, 歌舞艺术精湛, 剧情设计新颖, 舞台灯光璀璨, 民族风情独特, 观众审美享受]
      壮族铜鼓舞歌舞剧《铜鼓的传说》: [铜鼓舞艺术, 歌舞结合完美, 角色塑造生动, 舞台动作有力, 传统文化弘扬, 观众情感沉浸]
      湘西土家族摆手歌舞剧《摆手歌》: [摆手舞艺术, 歌舞表演热情奔放, 剧情发展扣人心弦, 舞台道具特色鲜明, 民族特色浓郁, 观众审美愉悦]
    地方小戏:
      绍兴莲花落《翠姐姐回娘家》: [莲花落艺术, 人物性格刻画细腻, 剧情设计巧妙, 舞台道具贴近生活, 地域文化彰显, 观众情感共鸣]
      福建莆仙戏《春草闯堂》: [莆仙戏魅力, 故事情节引人入胜, 角色塑造立体, 舞台布景古朴典雅, 文化内涵深厚, 观众审美享受]
      湖南花鼓戏《刘海砍樵》: [花鼓戏艺术, 神话故事再现, 人物形象鲜明, 舞台动作灵动, 传统文化弘扬, 观众情感沉浸]
      广东粤剧《帝女花》: [粤剧艺术瑰宝, 历史故事演绎, 人物命运波折, 舞台效果震撼, 音乐旋律悠扬, 观众审美愉悦]
      安徽黄梅戏《天仙配》: [黄梅戏魅力, 爱情故事凄美, 角色关系复杂, 舞台灯光映衬, 表演艺术精湛, 观众情感体验]
  曲艺:
    说唱艺术:
      相声《逗你玩》: [语言幽默诙谐, 情节设计巧妙新颖, 表演技巧高超自然, 观众互动频繁热烈, 文化内涵丰富多元, 笑料不断引人入胜]
      评书《三国演义》: [历史故事再现生动, 情节跌宕起伏扣人心弦, 人物形象鲜明立体, 口语表达生动形象, 文化知识普及广泛, 听众沉浸体验深刻]
      快板《打枣》: [节奏明快富有感染力, 韵律感强烈吸引人, 表演形式活泼多样, 故事情节简洁明了, 文化元素巧妙融入, 观众节奏共鸣强烈]
      天津时调《摔西瓜》: [时调独特韵味悠长, 情节设计贴近生活, 表演风格风趣幽默, 角色塑造生动鲜活, 文化底蕴深厚, 观众笑声连连]
      山东快书《武松传》: [快书节奏紧凑有力, 故事情节引人入胜, 角色性格鲜明突出, 表演技巧高超精湛, 文化元素丰富多样, 观众掌声不断]

    鼓曲类:
      京韵大鼓《长坂坡》: [鼓声激昂振奋人心, 唱腔悠扬动听感人, 故事情节紧凑连贯, 角色塑造立体饱满, 舞台效果震撼人心, 传统文化弘扬有力]
      梅花大鼓《黛玉葬花》: [鼓点细腻富有情感, 唱腔婉转深情动人, 情感表达深刻细腻, 舞台布景诗意盎然, 文化内涵深厚丰富, 观众情感共鸣强烈]
      西河大鼓《三侠五义》: [鼓声雄浑有力, 唱腔激昂慷慨, 故事情节跌宕起伏, 角色性格鲜明立体, 文化元素融入巧妙, 观众热血沸腾]
      河南坠子鼓《王小赶脚》: [坠子鼓音色独特, 唱腔深情并茂富有感染力, 故事情节生动有趣, 角色塑造鲜活立体, 文化传承有力, 观众陶醉其中]
      温州鼓词《陈十四娘娘》: [鼓词韵律悠扬, 唱腔深情动人, 故事情节神秘传奇, 角色形象鲜明立体, 文化底蕴深厚, 观众听得入迷]
    琴书类:
      山东琴书《梁祝》: [琴音悠扬动听如泣如诉, 唱腔深情并茂感人肺腑, 故事情节凄美动人, 角色性格鲜明立体, 舞台灯光映衬如画, 观众情感沉浸其中]
      河南坠子琴书《王二姐思夫》: [坠子琴书特色鲜明, 唱腔深情细腻如丝如缕, 故事情节感人至深, 角色塑造立体生动, 文化元素丰富多样, 观众情感体验深刻]
      安徽琴书《孟姜女哭长城》: [琴书旋律悠扬动听, 唱腔深情悲壮感人, 故事情节跌宕起伏扣人心弦, 角色性格鲜明突出, 文化内涵深厚丰富, 观众泪眼婆娑]
      徐州琴书《水漫金山寺》: [琴书节奏明快有力, 唱腔激昂慷慨激昂, 故事情节紧张刺激引人入胜, 角色塑造立体鲜活, 文化元素巧妙融入, 观众热血沸腾]
      四川扬琴《秋江》: [扬琴音色清脆悦耳, 唱腔悠扬动听富有诗意, 故事情节优美动人, 角色性格鲜明立体, 舞台布景如画如诗, 观众陶醉其中]
    道情类:
      湖南渔鼓《洞庭秋思》: [渔鼓特色鲜明韵味悠长, 唱腔悠扬婉转深情动人, 情感表达细腻入微扣人心弦, 舞台布景诗意盎然如梦如幻, 地域文化彰显独特魅力, 观众情感共鸣强烈]
      四川竹琴《竹枝词》: [竹琴音色独特韵味十足, 唱腔深情并茂富有感染力, 故事情节生动有趣引人入胜, 角色性格鲜明立体栩栩如生, 文化传承有力深入人心, 观众审美享受愉悦]
      河南道情《王金豆借粮》: [道情旋律悠扬动听富有韵味, 唱腔深情细腻感人肺腑, 故事情节贴近生活真实感人, 角色塑造立体鲜活栩栩如生, 文化元素融入巧妙自然, 观众听得如痴如醉]
      浙江道情《英台哭坟》: [道情旋律优美动人, 唱腔深情如泣如诉, 故事情节感人至深, 角色塑造立体饱满, 文化传承有力, 观众深受感动]
      陕北道情《张连卖布》: [道情特色鲜明, 唱腔高亢激昂, 故事情节生动有趣, 角色性格鲜明, 地域文化彰显, 观众听得津津有味]
    牌子曲类:
      单弦牌子曲《风雨归舟》: [单弦独特韵味悠扬动听, 唱腔深情细腻如泣如诉, 故事情节引人入胜扣人心弦, 舞台灯光映衬如画如诗, 文化内涵深厚丰富, 观众审美愉悦享受]
      扬州清曲《扬州慢》: [清曲悠扬动听富有诗意, 唱腔深情细腻如丝如缕, 故事情节优美动人如诗如画, 舞台布景古色古香典雅大气, 文化元素丰富多样, 众情感体验深刻]
      福州伬艺《茶童戏主》: [伬艺旋律优美动人, 唱腔深情细腻富有韵味, 故事情节生动有趣引人入胜, 角色塑造立体鲜活栩栩如生, 地域文化彰显独特魅力, 观众听得如痴如醉]
      广东南音《客途秋恨》: [南音旋律悠扬动听富有南国风情, 唱腔深情细腻如泣如诉, 故事情节感人至深扣人心弦, 角色性格鲜明立体栩栩如生, 文化元素融入巧妙自然, 观众深受感动]
      广西文场《刘三姐》: [文场旋律清新明快富有民族特色, 唱腔深情激昂富有感染力, 故事情节生动曲折引人入胜, 角色塑造立体鲜活栩栩如生, 文化传承有力深入人心, 观众听得热血沸腾]
  传统美术:
    绘画类:
      国画《山水图》: [艺术风格独特, 笔墨技巧精湛, 自然景观再现, 文化内涵深厚, 情感表达细腻, 收藏价值高]
      年画《福寿双全》: [节日氛围浓厚, 色彩鲜艳明快, 寓意吉祥如意, 民间故事融入, 制作工艺考究, 文化传承有序]
      壁画《飞天神韵》: [历史背景深厚, 艺术表现手法多样, 人物形象生动, 色彩搭配和谐, 故事情节丰富, 文化价值显著]
      工笔画《花鸟图》: [细节描绘精致, 线条流畅自然, 花鸟形象栩栩如生, 色彩搭配典雅, 情感寓意深刻, 艺术审美价值]
      水墨画《渔舟唱晚》: [水墨韵味十足, 意境深远悠长, 自然风光再现, 情感表达含蓄, 创作技法独特, 文化底蕴丰富]
    雕塑类:
      石雕《龙柱》: [石材选择讲究, 雕刻技法精湛, 龙形栩栩如生, 寓意权威吉祥, 装饰效果突出, 文化象征明显]
      木雕《观音像》: [木质温润细腻, 雕刻线条流畅, 观音形象慈悲, 寓意平安吉祥, 工艺精湛绝伦, 文化底蕴深厚]
      泥塑《西游记人物》: [泥质柔软可塑, 人物形象生动, 故事情节再现, 色彩搭配活泼, 民间文化融入, 观众情感共鸣]
      玉雕《玉如意》: [玉石质地温润, 雕刻工艺精湛, 如意形状寓意吉祥, 色彩自然和谐, 情感表达含蓄, 收藏价值极高]
      牙雕《龙舟》: [象牙材质珍贵, 雕刻技法繁复, 龙舟形象逼真, 寓意团结奋进, 装饰效果华丽, 文化内涵丰富]
    剪纸与刻纸:
      剪纸《窗花》: [纸张选择多样, 剪纸技法熟练, 图案寓意吉祥, 装饰效果突出, 民间文化体现, 节日氛围浓厚]
      刻纸《十二生肖》: [刻纸技艺精湛, 生肖形象生动, 寓意吉祥如意, 色彩搭配和谐, 民间故事融入, 观众情感共鸣]
      剪纸《牡丹富贵》: [牡丹形象逼真, 剪纸线条流畅, 寓意富贵吉祥, 色彩鲜艳明快, 民间文化传承, 收藏价值显著]
      刻纸《花鸟图》: [花鸟形象栩栩如生, 刻纸技法细腻, 寓意自然和谐, 色彩搭配典雅, 情感表达含蓄, 艺术审美价值]
      剪纸《人物故事》: [人物形象生动传神, 剪纸线条有力, 故事情节丰富, 色彩搭配活泼, 民间文化融入, 观众审美享受]
    刺绣与织锦:
      苏绣《花鸟屏风》: [绣线选择讲究, 刺绣技法精湛, 花鸟形象逼真, 色彩搭配和谐, 图案寓意吉祥, 装饰效果华丽]
      湘绣《狮子滚绣球》: [绣线色彩丰富, 刺绣线条流畅, 狮子形象威武, 寓意吉祥如意, 民间文化体现, 观众情感共鸣]
      蜀锦《龙凤呈祥》: [锦缎质地细腻, 织锦技法繁复, 龙凤形象威严, 寓意权威吉祥, 装饰效果突出, 文化象征明显]
      苗绣《蝴蝶妈妈》: [苗族文化融入, 绣线色彩鲜艳, 蝴蝶形象生动, 寓意生命繁衍, 民间故事再现, 观众审美享受]
      云锦《花鸟图》: [云锦工艺独特, 花鸟形象栩栩如生, 色彩搭配典雅, 图案寓意美好, 装饰效果优雅, 文化底蕴深厚]
    民间工艺:
      风筝《蜈蚣风筝》: [风筝形状独特, 制作工艺精湛, 飞行效果稳定, 寓意长寿吉祥, 民间文化体现, 观众情感共鸣]
      皮影《三国演义》: [皮影形象生动, 制作工艺繁复, 故事情节丰富, 色彩搭配和谐, 民间文化融入, 观众审美享受]
      泥人《张飞》: [泥人形象传神, 制作工艺细腻, 人物性格突出, 色彩搭配活泼, 民间故事再现, 观众情感沉浸]
      糖画《动物世界》: [糖画技法精湛, 动物形象逼真, 色彩鲜艳明快, 寓意吉祥如意, 民间文化体现, 节日氛围浓厚]
      面塑《寿桃》: [面塑材质柔软可塑, 寿桃形象逼真, 寓意长寿吉祥, 色彩搭配和谐, 民间文化传承, 观众情感共鸣]
  传统技艺:
    手工艺:
      陶瓷制作《青花瓷瓶》: [传统工艺精髓, 色彩丰富多样, 造型优雅别致, 手工技艺精湛, 文化内涵深厚, 收藏价值极高]
      木雕工艺《龙凤呈祥》: [木雕艺术瑰宝, 图案寓意吉祥, 雕刻细腻入微, 材质选择讲究, 传统文化传承, 装饰效果突出]
      剪纸艺术《窗花图案》: [民间手工艺, 图案精美绝伦, 剪刀技艺高超, 纸张材质多样, 节日氛围营造, 传统文化弘扬]
      刺绣工艺《百鸟朝凤》: [刺绣艺术典范, 针法灵活多变, 色彩鲜艳夺目, 图案寓意美好, 传统文化精髓, 收藏观赏皆宜]
      泥塑艺术《寿星老翁》: [泥塑技艺独特, 人物形象生动, 色彩搭配和谐, 材质质感自然, 传统文化韵味, 民俗风情展现]
    酿造与酿造技术:
      酿酒技术《茅台酱香》: [传统酿造工艺, 酒香浓郁持久, 口感醇厚绵柔, 原料选择严格, 酿造周期漫长, 文化底蕴深厚]
      酿醋技术《山西老陈醋》: [传统酿醋工艺, 醋香浓郁醇厚, 口感酸爽开胃, 原料发酵充分, 酿造过程复杂, 地域特色鲜明]
      酱油酿造《传统酱油》: [酱油酿造技艺, 酱香浓郁独特, 口感鲜美醇厚, 原料选取讲究, 酿造时间长久, 调味品中翘楚]
      蜂蜜酿制《野生蜂蜜》: [蜂蜜酿制技术, 蜂蜜甜润可口, 营养丰富全面, 采集过程艰辛, 酿造环境纯净, 天然健康之选]
      茶叶发酵《普洱茶》: [茶叶发酵工艺, 茶香浓郁独特, 口感醇厚回甘, 茶叶储存讲究, 发酵过程复杂, 茶文化精髓]
    编织与刺绣技术:
      竹编技术《竹篮编织》: [竹编技艺精湛, 竹篮造型美观, 材质环保耐用, 编织手法多样, 传统文化传承, 生活实用性强]
      草编技术《草帽编织》: [草编技艺独特, 草帽遮阳透气, 材质轻盈柔软, 编织图案丰富, 民俗风情浓郁, 夏季必备良品]
      刺绣技术《苏绣屏风》: [苏绣技艺精湛, 屏风图案精美, 色彩搭配和谐, 针法灵活多变, 传统文化精髓, 家居装饰佳品]
      针织技术《手工毛衣》: [针织技艺传统, 毛衣温暖舒适, 材质选择多样, 图案设计新颖, 手工编织独特, 冬季保暖必备]
      绳结编织《中国结》: [绳结编织技艺, 中国结寓意吉祥, 造型美观大方, 材质选择多样, 编织手法灵活, 家居装饰优选]
    建筑技艺:
      古建筑修复《故宫修缮》: [古建筑修复技艺, 故宫历史厚重, 修复过程严谨, 材质选择讲究, 传统文化传承, 历史遗迹保护]
      传统民居建造《四合院》: [传统民居建造技艺, 四合院布局合理, 建筑材料环保, 施工工艺精湛, 传统文化体现, 居住环境舒适]
      园林设计《苏州园林》: [园林设计技艺, 苏州园林精美绝伦, 设计理念独特, 植被搭配和谐, 建筑风格典雅, 历史文化底蕴]
      石雕艺术《石狮雕刻》: [石雕技艺精湛, 石狮形象威严, 雕刻手法细腻, 材质选择讲究, 传统文化传承, 建筑装饰佳品]
      木构建筑《古桥建造》: [木构建筑技艺, 古桥造型优美, 结构稳固耐用, 木材选择讲究, 施工工艺复杂, 历史文化遗产]
    其他传统技艺:
      茶艺《功夫茶冲泡》: [茶艺技艺精湛, 功夫茶口感醇厚, 冲泡过程讲究, 茶具选择多样, 茶文化体验, 心灵放松之选]
      制墨技术《徽墨制作》: [制墨技艺传统, 徽墨墨色浓郁, 书写流畅自如, 原料选择严格, 制作工艺复杂, 书法绘画必备]
      制纸技术《宣纸制造》: [制纸技艺精湛, 宣纸质地柔韧, 书写绘画皆宜, 原料选择讲究, 制作工艺独特, 传统文化载体]
      风筝制作《潍坊风筝》: [风筝制作技艺, 潍坊风筝造型多样, 飞行稳定持久, 制作材料环保, 传统文化弘扬, 亲子活动优选]
      陶艺制作《陶艺拉坯》: [陶艺制作技艺, 拉坯造型独特, 材质质感自然, 制作过程有趣, 传统文化体验, 创意发挥空间]
  传统医药:
    中医理论:
      阴阳五行: [中医哲学基石, 强调阴阳平衡, 五行相生相克理论, 指导人体机能调节, 预测预防疾病, 揭示生命活动规律]
      脏腑经络: [解析人体内部结构, 阐述脏腑功能, 揭示经络运行规律, 明确气血循环路径, 作为疾病诊断依据, 拓展治疗思路]
      气血理论: [气血为生命能量基础, 解析气血生成与分布, 探究气血失衡原因, 提供调节气血方法, 确立养生保健原则, 指导疾病治疗]
      病因病机: [深入探索疾病成因, 明确病邪入侵途径, 评估机体抗病能力, 阐述疾病演变过程, 分类病因病机, 指导治疗方法选择]
      治则治法: [确立治疗原则, 分类治疗方法, 遵循方剂配伍原则, 应用针灸推拿, 指导中药煎服方法, 制定康复调理措施]
    中药学:
      采集时节: [选择药材最佳采集时机, 考虑季节对药效影响, 判断药材成熟度, 选择适宜采集方法, 掌握药材保存技巧, 确保药效最大化]
      炮制工艺: [明确炮制目的, 采用多样炮制方法, 提升药效原理, 降低毒性途径, 提升药材品质, 确保临床应用效果]
      配伍禁忌: [阐述药物相互作用, 遵循配伍原则, 列举禁忌药物, 协同发挥药效, 制约毒性, 确保临床用药安全]
      药性归经: [定位药物功效, 应用归经理论, 关联脏腑经络, 明确药效发挥途径, 指导临床用药, 确定疾病治疗方向]
      剂量用法: [确定药物剂量, 选择煎服方法, 控制药效持续时间, 优化药效峰值, 注意用药禁忌, 评估用药效果]
    针灸疗法:
      针刺技法: [技法多样, 针具适宜, 深度精准, 角度恰当, 感应灵敏, 疗效显著]
      艾灸疗法: [阐述艾灸原理, 分类艾灸方法, 选择艾灸适应症, 注意艾灸禁忌, 评估艾灸效果, 考量艾灸安全性]
      拔罐疗法: [分析拔罐原理, 应用拔罐方法, 选择拔罐适应症, 注意拔罐禁忌, 评估拔罐效果, 提升拔罐舒适度]
      耳针疗法: [探索耳针原理, 定位耳部穴位, 选择耳针适应症, 注意耳针禁忌, 评估耳针疗效, 强调耳针操作简便性]
      电针疗法: [介绍电针原理, 选择电针设备, 设置电针参数, 选择电针适应症, 注意电针禁忌, 提升电针疗效]
    推拿按摩:
      手法技巧: [技巧多样, 选择合理, 力度精准, 频率恰当, 效果显著, 安全保障]
      穴位疗法: [准确定位穴位, 解析穴位功能, 选择穴位刺激方法, 选择穴位适应症, 注意穴位禁忌, 评估穴位疗效]
      经络疏通: [阐述经络疏通原理, 应用经络疏通方法, 选择经络疏通适应症, 注意经络疏通禁忌, 评估经络疏通效果, 提升经络疏通舒适度]
      肌肉放松: [解析肌肉放松原理, 应用肌肉放松方法, 选择肌肉放松适应症, 注意肌肉放松禁忌, 评估肌肉放松效果, 提升肌肉放松舒适度]
      保健养生: [倡导保健养生理念, 应用推拿养生方法, 选择推拿养生适应症, 注意推拿养生禁忌, 评估推拿养生效果, 强调推拿养生便捷性]
      康复技术: [展示康复技术多样性, 选择适宜康复方法, 分析康复适应症, 注意康复禁忌, 评估康复效果, 关注康复技术前沿]
    养生与康复:
      饮食调养: [制定个性化营养方案, 选择季节性食材, 遵循膳食平衡原则, 促进消化吸收, 制定疾病预防策略, 提升身体机能]
      运动锻炼: [领悟太极拳精髓, 掌握八段锦动作标准, 加速气血循环, 全面增强体质, 实现身心和谐平衡, 辅助慢性病康复]
      情志调节: [提供冥想静心方法, 应用书法艺术疗法, 制定情绪平衡策略, 缓解心理压力, 提升精神面貌, 改善生活质量]
      康复技术: [阐述物理治疗理论, 实施作业疗法, 明确功能恢复路径, 监测康复效果, 制定个性化康复策略, 强化生活自理能力]
      季节养生: [顺应自然法则, 汲取四季养生智慧, 调整生活习惯, 制定疾病预防策略, 优化身体机能, 实现身心和谐共生]
  传统体育、游艺与杂技:
    武术类:
      太极拳: [内外兼修, 柔中带刚, 养生健身, 武术哲学, 文化传承, 国际影响力]
      少林功夫: [历史悠久, 拳法多样, 武德并重, 实战性强, 影视传播, 国际交流]
      武当武术: [道家思想, 内外兼修, 拳剑并重, 养生修炼, 门派特色, 文化底蕴]
      形意拳: [注重实战, 拳理深奥, 发力迅猛, 内外合一, 传承有序, 武术精神]
      咏春拳: [短桥窄马, 攻防兼备, 实战性强, 拳法独特, 电影推广, 武术文化]
    球类运动:
      蹴鞠: [古代体育遗产, 竞技性强, 团队合作, 历史传承, 文化象征, 体育精神]
      毽球: [技巧性强, 全身运动, 娱乐性强, 民间传统, 竞技比赛, 健身效果]
      马球: [古代贵族运动, 骑术与球技结合, 竞技激烈, 历史文化, 传承发展, 体育精神]
      藤球: [东南亚特色运动, 技巧与力量并重, 团队协作, 文化交流, 竞技比赛, 健身娱乐]
      板球: [团队竞技项目, 战术多变, 身体素质要求高, 历史文化, 国际赛事, 体育精神]
    棋类游戏:
      围棋: [策略性强, 变化无穷, 智力挑战, 文化传承, 国际交流, 修身养性]
      象棋: [历史文化悠久, 战术策略丰富, 智力博弈, 民间传统, 竞技比赛, 文化象征]
      国际象棋: [全球通行棋类, 逻辑思维训练, 战术策略, 国际比赛, 文化交流, 智力挑战]
      跳棋: [家庭娱乐游戏, 规则简单易懂, 智力开发, 亲子互动, 竞技比赛, 休闲娱乐]
      五子棋: [对弈快速激烈, 智力挑战, 规则简洁明了, 竞技性强, 文化内涵, 休闲娱乐]
    杂技表演:
      魔术: [视觉艺术, 创意无限, 手法技巧, 表演魅力, 观众互动, 文化娱乐]
      杂技: [高难度动作, 惊险刺激, 身体素质要求高, 技巧性强, 表演艺术, 文化传承]
      马戏: [动物表演, 技巧精湛, 观赏性强, 历史文化, 生态保护, 娱乐教育]
      柔术: [身体柔韧极限, 表演艺术性, 技巧性强, 身体素质要求高, 视觉震撼, 文化传承]
      平衡术: [技巧与平衡并重, 表演艺术性, 心理素质要求高, 视觉享受, 文化内涵, 休闲娱乐]
    民间游戏:
      跳绳: [全身运动, 节奏感强, 健身效果好, 亲子互动, 竞技比赛, 休闲娱乐]
      踢毽子: [下肢锻炼, 技巧性强, 娱乐性好, 民间传统, 竞技比赛, 健身效果]
      迷藏: [智力与体力结合, 团队协作, 娱乐性强, 童年回忆, 亲子互动, 社交能力]
      翻花绳: [手部灵活度训练, 创造力培养, 亲子互动, 传统文化, 休闲娱乐, 智力开发]
      投壶: [古代礼仪游戏, 技巧性挑战, 历史文化, 娱乐性强, 亲子互动, 社交能力]
    牌子曲类:
      单弦牌子曲: [北京特色曲种, 叙事性强, 唱腔独特, 历史文化, 民间传统, 艺术魅力]
      扬州清曲: [江苏传统音乐, 唱腔婉转, 情感表达细腻, 历史文化, 传承发展, 艺术欣赏]
      四川清音: [四川地方曲艺, 唱腔清新, 表演生动, 历史文化, 地域特色, 娱乐休闲]
      河南坠子: [河南传统曲种, 唱腔高亢激昂, 叙事性强, 历史文化, 民间传统, 艺术传承]
      天津时调: [天津地方曲艺, 唱腔独特, 幽默风趣, 历史文化, 地域特色, 娱乐文化]
  民俗:
    节日庆典类:
      春节: [内外欢聚, 传统习俗, 家庭团聚, 放鞭炮贴春联, 年夜饭丰盛, 文化传承]
      中秋节: [月圆团圆, 赏月吃饼, 家庭聚会, 灯笼高挂, 嫦娥传说, 民俗风情]
      端午节: [纪念屈原, 赛龙舟吃粽子, 挂艾草佩香囊, 驱邪祈福, 历史文化, 民俗特色]
      元宵节: [赏花灯猜灯谜, 吃汤圆团圆, 舞狮舞龙祈福, 节日氛围, 民俗传承, 文化娱乐]
      清明节: [祭祖扫墓缅怀, 踏青游玩插柳, 寒食禁火, 历史文化, 民俗风情, 家族团聚]
    婚丧嫁娶类:
      婚俗: [传统婚礼仪式, 媒妁之言父母命, 迎亲拜堂, 红烛高照, 民俗传承, 家庭融合]
      丧俗: [缅怀逝者守灵, 出殡安葬服丧, 纸钱祭祀, 灵魂超度, 历史文化, 民俗风情]
      嫁娶习俗: [嫁妆准备迎娶, 婚礼宴席洞房, 婚后回门, 家族融合, 民俗传统, 社会影响]
      订婚习俗: [双方家长见面, 交换信物定婚期, 媒人协调, 情感升温, 民俗习惯, 社会风气]
      离婚习俗: [协商处理财产, 子女抚养协议, 情感解脱, 社会影响, 民俗变迁, 家庭关系]
    饮食习俗类:
      地方特色饮食: [地域风味独特, 食材制作工艺, 口味偏好文化, 节日食品传统, 民俗风情, 饮食习惯]
      饮食礼仪: [餐桌礼仪顺序, 餐具使用文化, 敬酒文化话题, 尊重长辈传统, 民俗习惯, 社会交往]
      茶文化: [品茗艺术选择, 泡茶技巧历史, 茶文化社交, 修身养性哲学, 民俗风情, 文化传承]
      酒文化: [酿酒工艺礼仪, 酒桌文化节日, 诗词歌赋情感, 民俗风情, 社会交往, 文化传承]
      节日饮食: [节日特色食品, 寓意吉祥习惯, 饮食习惯氛围, 家族团聚文化, 民俗传统, 文化娱乐]
    信仰习俗类:
      民间信仰: [神灵崇拜祭祀, 风水观念符咒, 祈福避邪传说, 民俗风情, 信仰传承, 社会文化]
      宗教仪式: [宗教节日活动, 祈祷仪式法门, 宗教教义传承, 信仰文化, 民俗风情, 社会影响]
      佛教信仰: [佛像供奉祈福, 禅修冥想报应, 轮回观念慈悲, 民俗风情, 文化传承, 社会影响]
      道教信仰: [道观修行制药, 符咒法术五行, 养生之道自然, 民俗风情, 文化传承, 社会观念]
      基督教信仰: [教堂礼拜忏悔, 圣经研读救赎, 爱心奉献传承, 民俗风情, 文化交流, 社会和谐]
    社会习俗类:
      民间禁忌: [行为言语禁忌, 色彩数字象征, 节日信仰禁忌, 民俗风情, 社会规范, 文化传承]
      习俗传承: [家族地域特色, 节日庆典婚丧, 饮食文化信仰, 民俗风情, 社会文化, 历史传承]
      社交礼仪: [见面拜访礼仪, 餐桌送礼场合, 尊重他人传统, 民俗风情, 社会交往, 文化内涵]
      民间娱乐: [戏曲舞蹈游戏, 节日庆典音乐, 民俗风情文化, 社会娱乐, 传统文化, 社交活动]
      民间手工艺: [传统工艺制品, 制作技艺发展, 地域特色文化, 民俗风情, 社会经济, 文化传承]